### ISSUE TITLE
Question about method plr_tolerance_check()

### ISSUE THREAD

**Issue by svareg** [openoereb/pyramid_oereb#718] opened 2018-12-11 13:54 UTC
Hello,

Sometimes, when creating an extract, the intersecting features are not listed in the "concerned themes".

I identified that the result of st_intersects() returns the right features from DB.
But then they are removed from the concerned theme in the function processor.plr_tolerance_check().
Actually, they are removed because they don't intersect exactly : there is a distance from 0.1 mm between the features, and the line if not exactly on the polygon edge.

Is this "normal" ?
I don't really understand why this check was added here. Can someone explain this ?
Why don't we just use the result of st_intersect sent by the DB ?
Perhaps should it be configurable ?

Thanks!

**Comment by voisardf** [comment] 2018-12-11 14:10
Hi Guillaume,

due to data quality there will always be false true's and true false's in the returned restriction features. So it was agreed in the "federal steering committee" that all features with less than a square meter of surface or less than 1m of length should be eliminated from the results as there are likely to be due to 'slivers' or other topology issues. If I recall it right, that's the reason for this check or am I wrong @vvmruder?

**Comment by svareg** [comment] 2018-12-11 14:20
Ok, I understand the explanation, but for us it has the following consequences :

That's what we see in our application. The forest perimeter is at the limit of many real estates :

![image](https://user-images.githubusercontent.com/36037102/49806232-757e6580-fd57-11e8-816e-ca1c0eb3746c.png)

And that's the real difference : 

![image](https://user-images.githubusercontent.com/36037102/49806385-ee7dbd00-fd57-11e8-8398-8882be417133.png)

The forest line is parrallel to the real estate edge at a distance of 0.01 mm. And because of this distance, it won't appear in extract.

I think the check function should be rewritten with a buffer check too.
What do you think ?

**Comment by voisardf** [comment] 2018-12-11 14:23
sorry, I forgot to mention that you can change this thresholds in the basic configuration of the standard yaml, like:

   - name: plr73
      code: LandUsePlans
      geometry_type: GEOMETRYCOLLECTION
      # Define the minmal area and length for public law restrictions that should be considered as 'true' restrictions
      # and not as calculation errors (false trues) due to topological imperfections
      thresholds:
        length:
          limit: 1.0
        area:
          limit: 1.0
      text:

**Comment by svareg** [comment] 2018-12-11 14:41
I've just found something strange in our data, perhaps the problem is actually only by us. 
I'll check this deeper...

**Comment by svareg** [comment] 2018-12-11 15:19
Also... there was actually nothing strange in our data... 

Therefore, the problem is right the one discribed above. 
I think it would be great if we were be able to configure if we want to activate this check or not.

**_Tip:_**

However, I've found a temporary solution (if there is any interest):
- Derive the DatabaseSource object in order to override the type of _plr_record_class object (will be PlrRecordBS)
- Derive PlrRecord (will be PlrRecordBS), so that you can redefine the calculate() method.

**Comment by vvmruder** [comment] 2021-04-09 13:21
This is a nice solution and thats what pyramid_oereb was designed for :)

But for the solution in a more generic way like you describe via a buffer, I fear we would introduce more complex questions. You dont think so? I Mean, a buffer would mean, that you will maybe catch in different places geometries which were correctly not recognized before.

**Comment by remyguillaume** [comment] 2021-09-21 12:26
After a discussion I just had with GeoInfo, I post here the changes I made to fix this problem at Basel-Stadt.

New file plrrecordbs.py:

```
from pyramid_oereb.lib.records.plr import PlrRecord
import shapely

class PlrRecordBS(PlrRecord):

    def calculate(self, real_estate):

        """ 
        override this function, so that we can deactivate the unnecessary intersects check (we want a custom one)
        see the following issue for further explanations : https://github.com/camptocamp/pyramid_oereb/issues/718
        """
        # Calculate intersection length values
        for geometry in list(self.geometries):
            # If the geometry is a Polygon, we test a minimal area intersection to know if the geometry is really concerned
            # If the geometry is a LineString or a Point, we do not test anything, the geometry is always concerned
            concerned = geometry.calculate(real_estate, self.min_length, self.min_area, self.length_unit, self.area_unit)
            if type(geometry.geom) is shapely.geometry.polygon.Polygon and not concerned:
                self.geometries.remove(geometry)
            
        # Points
        nr_of_points = self._sum_points()
        self._nr_of_points = nr_of_points if nr_of_points else None

        # Lines
        length_share = self._sum_length()
        if length_share is None:
            self._length_share = None
        else:
            self._length_share = int(round(length_share, 0))
            
        # Areas
        area_share = self._sum_area()
        if area_share is None:
            self._area_share = None
            self.part_in_percent = None
        else:
            self._area_share = int(round(area_share, 0))
            self.part_in_percent = round(
                ((float(self._area_share) / float(real_estate.land_registry_area)) * 100),
                1
            )

        return len(self.geometries) > 0
```

New file plr.py:

```
from .plrrecordbs import PlrRecordBS

class DatabaseSourceBS(DatabaseSource):
    _plr_record_class = PlrRecordBS
```

Then, use this new class as source in the config.yaml file :

```
source:
        class: pyramid_oereb_bs.models.datasources.DatabaseSourceBS
```

Some information may be missing for the correct integration in pyramid_oereb, but the most important should be here.

**Comment by jwkaltz** [comment] 2021-09-27 08:57
Thanks for your contribution @remyguillaume , so, put another way, your solution is to do the tolerance check only for polygons.

In fact, when we were discussing the issue with Max from Geoinfo last time, we came to the conclusion that indeed the tolerance check is probably generally unwanted for lines and points. So this is consistent with what you wrote.

I wonder if we should implement that as standard, what do you think @voisardf @kdeininger , maybe others?

**Comment by MaxHoeferGEOINFO** [comment] 2021-09-27 10:54
Hi @remyguillaume, thanks a lot for sharing your code. 

When I remember correctly our call, then you mentioned, that you made changes to the st_intersect tolerance, to influence the behaviour, right? Was this done similarly like explained here? 
https://gis.stackexchange.com/questions/236712/change-st-intersects-default-tolerance

Also, maybe it would make sense to allign the settings used. Could you share what tolerances you defined now? 
I will additionally discuss with the canton, what settings they prefer. 
Cheers - Max

**Comment by vvmruder** [comment] 2022-12-15 13:50
@svamaa Please check if the current solution fits your needs. Close if everything is satisfied.

**Comment by jwkaltz** [comment] 2022-12-15 14:06
Note that with the new configuration options (https://github.com/openoereb/pyramid_oereb/blob/bd4d87867fe8d5fa75795486e65ba0e9dadac41d/dev/config/pyramid_oereb.yml.mako#L619-L630) it should no longer be necessary to override the st-intersects function in Postgres.

**Comment by vvmruder** [comment] 2022-12-15 14:12
Thank you for this info. I close this. @svamaa please reopen if necessary.

**Closed by vvmruder** 2022-12-15 14:12 UTC
Labels: discussion
