### ISSUE TITLE
Vertical Alignement of Line-Symbols imported with import_federal_topic

### ISSUE THREAD

**Issue by thomasmarti** [openoereb/pyramid_oereb#902] opened 2019-08-28 07:03 UTC
Line-symbols displayed in the legend (pdf static extract) should be aligned in the center of the legend box.

This problem occurs when the data is imported with the import_federal_topic tool. The imported image (see below) has no margins. In contrast, the line-symbol images of the cantonal data (AG) have margins, so that this problem does not have any effect.

**actual:**
![image](https://user-images.githubusercontent.com/17591098/63833615-c086ea00-c973-11e9-9afc-b8a5969f6427.png)

**expected:**
![image](https://user-images.githubusercontent.com/17591098/63833555-a0572b00-c973-11e9-858e-23c8c942388a.png)

**base64 Image from table motorways_building_lines.legend_entry:**
iVBORw0KGgoAAAANSUhEUgAAAJgAAAAICAYAAAAFpDZiAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVFhH7dLBCYAwDIXhN4qjOEpHcTOXsXUMBQnkkNJbIZX/gwe9NCTwBAA/0vSkTNVhG0ZNp72iW1uYlSWXim0ZjW/aw6wsGd306X3KEArmKNiEUDBHwSaEgrmlCwYAa5Be0fKFqvunu1wAAAAASUVORK5CYII=

**Comment by thomasmarti** [comment] 2019-08-28 07:22
This problem has been noted by swisstopo during the final inspection of our system

**Comment by jwkaltz** [comment] 2019-09-02 07:19
@vvmruder @ralphschulerSZ @svareg @voisardf @romefi @peterschaer do you have this problem as well?

**Comment by svareg** [comment] 2019-09-02 07:27
Hi there,

Yes, we have the same here at BS:

![grafik](https://user-images.githubusercontent.com/36037102/64097150-babe4980-cd63-11e9-82f4-f2fc88d0b480.png)

**Comment by voisardf** [comment] 2019-09-02 10:15
Hi all,
I had to invent some data, but yes, we have the same behaviour.

**Comment by vvmruder** [comment] 2019-09-02 10:22
We have this too. In the moment I would say, this is a wrongly provided image size. Since we only import the images provided by data download from federal sources. Should we file a "bug" or does someone has other ideas?

Image which comes down of federal sources is:

![inForce](https://user-images.githubusercontent.com/3714179/64108062-27ddd900-cd7c-11e9-88fe-86de7ddd3d2a.png)

This is clearely not matching specification which says: 30x70px (or something like that)

**Comment by peterschaer** [comment] 2019-09-02 10:56
We don't use `import_federal_topic`. Therefore I can't reproduce the error.

**Comment by vvmruder** [comment] 2019-09-02 11:22
@peterschaer: Do you have another way to import the data? And are you handeling the images deliverd by the fedaral data set in a special way?

**Comment by peterschaer** [comment] 2019-09-02 11:29
We don't use the images provided by the federal data. We use our own, because we need our legend images to be quadratic and not rectangular.

**Comment by vvmruder** [comment] 2019-09-02 11:30
Ok. Thanks

**Comment by kdeininger** [comment] 2019-09-02 11:33
If I decode the image from the first comment using the command line, I get a 152x8 pixel sized image:

```
echo "iVBORw0KGgoAAAANSUhEUgAAAJgAAAAICAYAAAAFpDZiAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVFhH7dLBCYAwDIXhN4qjOEpHcTOXsXUMBQnkkNJbIZX/gwe9NCTwBAA/0vSkTNVhG0ZNp72iW1uYlSWXim0ZjW/aw6wsGd306X3KEArmKNiEUDBHwSaEgrmlCwYAa5Be0fKFqvunu1wAAAAASUVORK5CYII=" | base64 --decode - > test.png
```

![test](https://user-images.githubusercontent.com/5467596/64111790-d33f5b80-cd85-11e9-9adb-1cb15471767b.png)

So I think this issue has to be related to the data.

**Comment by vvmruder** [comment] 2019-09-03 10:23
Who is contacting federal office?

**Comment by thomasmarti** [comment] 2019-09-19 06:02
I will contact Rolf Zürcher and send him the Link to this Issue.

**Comment by vvmruder** [comment] 2019-10-10 06:59
@thomasmarti Do you have any news on that?

**Comment by kdeininger** [comment] 2019-10-28 14:38
Maybe related to #876.

**Comment by pramisters** [comment] 2019-10-28 16:20
No it's not related to #876.
The symbol image simply doesn't comply with the federal specification.
The Rahmenmodells says: 300dpi and the "Weisung statischer Auszug": 6x3mm
That means: 71x35 px

- The KbS symbols (KbS_Codetexte_V1_4.xml) are correct: 71x35
- The PGS symbols (PlanerischerGewaesserschutz_Codetexte_V1_1.xml) are wrong: 185x117, 188x116
- And as stated above, the symbol for Baulinien Nationalstrassen is wrong: 152x8

At least the aspect ratio (2:1) should be correct.

**Comment by vvmruder** [comment] 2021-04-09 13:57
So how is it going here? Are the images still corrupt?

**Comment by vvmruder** [comment] 2022-12-15 13:56
Symbol was fixed by FED.

**Closed by vvmruder** 2022-12-15 13:56 UTC
